### ISSUE TITLE
Grammars clashing with Linguist

### ISSUE THREAD

**Issue by lildude** [Alhadis/language-grammars#1]
Woohoo!!! First issue!! 🎉  😁 

I'm in the process of preparing for Linguist 7.6.0 and I've just updated all the grammars and this repo, used by several grammars in Linguist, has been flagged by the grammar compiler:

- [ ] repository `vendor/grammars/ABNF.tmbundle` (from https://github.com/sanssecours/ABNF.tmbundle) (1 errors)
    - [ ] Duplicate scope in repository: scope `source.abnf` was already defined in repository `vendor/grammars/language-grammars` (from https://github.com/Alhadis/language-grammars)

- [ ] repository `vendor/grammars/EBNF.tmbundle` (from https://github.com/sanssecours/EBNF.tmbundle) (1 errors)
    - [ ] Duplicate scope in repository: scope `source.ebnf` was already defined in repository `vendor/grammars/language-grammars` (from https://github.com/Alhadis/language-grammars)

- [ ] repository `vendor/grammars/language-grammars` (from https://github.com/Alhadis/language-grammars) (1 errors)
    - [ ] Missing include in grammar: `source.lex.regexp` (in `grammars/lex-regexp.cson`) attempts to include `escapes` but the scope cannot be found

The easy solution is to _not_ bump the SHA for this submodule, but the two grammars at the top may be better than what we're already using in Linguist so maybe a few switcheroo PRs are needed for Linguist?

**Comment by Alhadis** [comment]
Ah yeah, I was going to include those as well when submitting the PR, but I noticed they weren't perfect, so I held off until I was sure they were. 😁

But, uh, that was actually going to be the plan... so most definitely. 😉

**Comment by Alhadis** [comment]
BTW, the scopes for the unused *BNF grammars weren't added to `grammars.yml`, so... how on Earth is Linguist still picking them up? 😕

**Comment by Alhadis** [comment]
Never mind. It's actually fortuitous this occurred, because I never noticed [how badly our ABNF grammar rendered certain files](https://github.com/TadiT7/xiaomi_violet_dump/blob/5edc11ebb2c4b5d9a4bfd5ebc335ee7e47f69f56/system/system/usr/srec/en-US/contacts.abnf)... :|

I'm installing our Docker image on a Ubuntu machine, and will give the compiler a whirl in a minute. Will be able to use this to test grammars *locally* and ensure stuff like this never happens again. 😅

**Comment by Alhadis** [comment]
Closing this since the original issue was resolved in github/linguist#4617, but let me know if you're still experiencing troubles. 👍
