### ISSUE TITLE
LBNF?

### ISSUE THREAD

**Issue by s5bug** [Alhadis/language-grammars#3]
LBNF would be nice so my https://bnfc.digitalgrammars.com/ grammars could be highlighted 😄

**Comment by Alhadis** [comment]
Thanks for letting me know. 👋 I'm not familiar with LBNF, so I'll need to set aside some time to read into it. Bear with me.

**Comment by Alhadis** [comment]
This turned out to be a *very* complex format, and the grammar I've written is no doubt riddled with holes and inconsistencies. 😞 Give me a holler if you spot any.
